CREATE DATABASE dbCRUDJS;

USE dbCRUDJS;

CREATE TABLE tbusuario (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  passe VARCHAR(100),
  dataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);